spring:
  application:
    name: cinema-booking-system

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT_EXTERNAL:5433}/${DB_NAME:cinema_booking}
    username: ${DB_USER:cinema_user}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  # Cấu hình gửi Email (Sử dụng Mailtrap.io để test môi trường dev)
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  signer-key: ${JWT_SECRET:default-dev-secret-key-32-chars-minimum}
  access-token-valid-duration: 3600
  refresh-token-valid-duration: 604800

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace