package com.cinema.booking.enums;

public enum PaymentEventType {
    PAYMENT_INITIATED,
    PAYMENT_REUSED,
    PAYMENT_URL_CREATED,
    VNPAY_CALLBACK_RECEIVED,
    VNPAY_CALLBACK_INVALID_SIGNATURE,
    VNPAY_AMOUNT_MISMATCH,
    MOMO_CALLBACK_RECEIVED,
    MOMO_CALLBACK_INVALID_SIGNATURE,
    MOMO_AMOUNT_MISMATCH,
    PAYMENT_ALREADY_PROCESSED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,
    PAYMENT_PROVIDER_ERROR
}
