package com.cinema.booking.enums;

public enum PaymentEventType {
    PAYMENT_INITIATED,
    PAYMENT_REUSED,
    PAYMENT_URL_CREATED,
    VNPAY_CALLBACK_RECEIVED,
    VNPAY_CALLBACK_INVALID_SIGNATURE,
    VNPAY_AMOUNT_MISMATCH,
    MOMO_CALLBACK_RECEIVED,
    MOMO_CALLBACK_INVALID_SIGNATURE,
    MOMO_AMOUNT_MISMATCH,
    SEPAY_WEBHOOK_RECEIVED,
    SEPAY_WEBHOOK_INVALID_SIGNATURE,
    SEPAY_AMOUNT_MISMATCH,
    SEPAY_PAYMENT_NOT_FOUND,
    PAYMENT_ALREADY_PROCESSED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,
    REFUND_REQUESTED,
    PAYMENT_PROVIDER_ERROR
}
