package com.cinema.booking.enums;

public enum PermissionName {

    MOVIE_VIEW,
    MOVIE_CREATE,
    MOVIE_UPDATE,
    MOVIE_DELETE,

    CINEMA_VIEW,
    CINEMA_CREATE,
    CINEMA_UPDATE,
    CINEMA_DELETE,

    ROOM_VIEW,
    ROOM_CREATE,
    ROOM_UPDATE,
    ROOM_DELETE,

    SEAT_VIEW,
    SEAT_CREATE,
    SEAT_UPDATE,
    SEAT_DELETE,

    SHOWTIME_VIEW,
    SHOWTIME_CREATE,
    SHOWTIME_UPDATE,
    SHOWTIME_DELETE,

    BOOKING_CREATE,
    BOOKING_VIEW_OWN,
    BOOKING_VIEW_ALL,
    BOOKING_CANCEL_OWN,
    BOOKING_CANCEL_ALL,
    BOOKING_UPDATE_STATUS,

    PAYMENT_CREATE,
    PAYMENT_VIEW_OWN,
    PAYMENT_VIEW_ALL,
    PAYMENT_REFUND,

    PROMOTION_VIEW,
    PROMOTION_CREATE,
    PROMOTION_UPDATE,
    PROMOTION_DELETE,

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_BLOCK,
    PROFILE_UPDATE,

    ROLE_MANAGE,
    PERMISSION_MANAGE,

    DASHBOARD_VIEW,
    REPORT_VIEW,
    ANALYTICS_VIEW,
    AUDIT_VIEW,

    TICKET_VIEW_OWN,
    TICKET_VIEW_ALL,
    TICKET_CHECKIN,

    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_REFRESH_TOKEN
}
